def features():
    print('**********Features**********\n\n'
          'Every round characters gain 5 rage. First skill also gives 5 rage. Here is the champs:'
          '===KEVIN===\n'
          'Passive: %20 crit chance\n'
          'Active passive: 2x attack below %50 hp\n'
          'Skill1: basic attack, gives 5 rage\n'
          'Skill2: 2x attack, takes 10 rage\n'
          'ult: 4x attack takes 50 rage \n\n'
          '===FARA===\n'
          'Passive: %20 dodge chance\n'
          'Active passive: 2x defence below %50 hp\n'
          'Skill1: basic attack, gives 5 rage\n'
          'Skill2: 1.5x defence for 1 round, and hits basic\n'
          'ult: Backs to full hp\n\n'
          '===KEN===\n'
          'Passive: %10 crit chance and %10 dodge chance\n'
          'Active passive: 1.5x attack and 1.5x defence below %50 hp\n'
          'Skill1: basic attack, gives 5 rage\n'
          'Skill2: +50 hp and basic attack, takes 10 rage\n'
          'Ult: 1.5 x attack and 1.5x defence for 1 round\n')
